#!/bin/bash

remote=git@github.com:incs741/project01.git
list=(hello sub sub2 otp)

x=0
while [ "x${list[x]}" != "x" ]
do
    branch=${list[$x]}
    rm -rf ../$branch
    git clone -b $branch $remote ../$branch
    x=$(( $x + 1 ))
done

